services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'bridge'
    group_add:
      - "105"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    volumes:
      - /var/lib/docker/volumes/50981fc98c1b16ea0496d46ee552fa3c8cfc4727adda3ac7237b207d56ff920f/_data:/config
      - /var/lib/docker/volumes/792a9ffbf717e9f9c7fa414e3193598f5a9b7b88ebc960714d939ac25cfd3120/_data:/cache
      - type: bind
        source: /media/noe/Media/Movies
        target: /movies
      - type: bind
        source: /media/golbat/Media/Shows
        target: /shows
    restart: 'unless-stopped'

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/debian/docker/vol/home_assisant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /var/lib/docker/volumes/595c3d8defc06a6ed4b15ca93c2e0c51d07a3c03e696c8fa0ce074e88b5aa0bc/_data:/config
      - /media/noe/Media/Movies:/Movies
      - /media/seed:/Seed
      - /media/golbat/Media/Shows:/Shows
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=debain.dukcdns.org
      - PASSWORD_HASH=$$2a$$12$$mHqvUP7UDU8T6Vm5D26PHuSeFkIaWerhvie/RXl2xBTtGPdo9GBFK
      - PORT=51821
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /home/debian/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
