services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "bridge"
    group_add:
      - "105"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: /media/noe/Media/Movies
        target: /movies
      - type: bind
        source: /media/golbat/Media/Shows
        target: /shows
    restart: "unless-stopped"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-data:/config
      - /media/noe/Media/Movies:/Movies
      - /media/seed:/Seed
      - /media/books:/Books
      - /media/golbat/Media/Shows:/Shows
      - /media/golbat/Media/Shows/Detective Conan:/Conan
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  portainer-data:
  jellyfin-config:
  jellyfin-cache:
  qbittorrent-data:
